parameters:
  - name: buildPrerelease
    type: boolean
    default: true

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  IsPrerelease: $[or(ne(variables['Build.SourceBranchName'], 'main'), ${{parameters.buildPrerelease}})]
  VersionSuffix: -$(Build.SourceBranchName)-$(Build.BuildNumber)
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:

- task: NuGetToolInstaller@1

- task: Cache@2
  displayName: Cache
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: '$(NUGET_PACKAGES)'
    cacheHitVar: 'CACHE_RESTORED'

- task: NuGetCommand@2
  displayName: 'NuGet restore'  
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:ContinuousIntegrationBuild=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: |
      **/*.Test.csproj
      **/FunicularSwitch.Generators.Consumer.csproj
      **/FunicularSwitch.Generators.Consumer.Nuget.csproj
      **/FunicularSwitch.Generators.Consumer.StandardMinLangVersion.csproj
      **/FunicularSwitch.Generators.FluentAssertions.Consumer.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SymbolServerType: TeamServices
    TreatNotIndexedAsWarning: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack funicular switch'
  inputs:
    command: pack
    nobuild: true
    packagesToPack: Source/FunicularSwitch/FunicularSwitch.csproj
    includesymbols: true
    includesource: true
    verbosityPack: Detailed

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack funicular generators'
  inputs:
    command: pack
    nobuild: true
    packagesToPack: Source/FunicularSwitch.Generators/FunicularSwitch.Generators.csproj
    packDirectory: '$(Build.ArtifactStagingDirectory)/Generators'
    verbosityPack: Detailed

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack funicular generators fluent assertions'
  inputs:
    command: pack
    nobuild: true
    packagesToPack: Source/FunicularSwitch.Generators.FluentAssertions/FunicularSwitch.Generators.FluentAssertions.csproj
    packDirectory: '$(Build.ArtifactStagingDirectory)/Generators.FluentAssertions'
    verbosityPack: Detailed

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: packages