//HintName: FunicularSwitch.Test.MonadA.g.cs
namespace FunicularSwitch.Test
{
    public static partial class MonadA
    {
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> Return<T0, T1, T2, T3, A>(global::System.Threading.Tasks.Task<A> a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>.Return((await a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> Return<T0, T1, T2, T3, A>(global::System.Threading.Tasks.ValueTask<A> a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>.Return((await a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> Bind<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>)(await ma)).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> Bind<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>)(await ma)).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B> SelectMany<T0, T1, T2, T3, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>)ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> SelectMany<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>)(await ma)).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> SelectMany<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>)(await ma)).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, C> SelectMany<T0, T1, T2, T3, A, B, C>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, C>> SelectMany<T0, T1, T2, T3, A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, C>> SelectMany<T0, T1, T2, T3, A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B> Map<T0, T1, T2, T3, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>.Return(fn(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> Map<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>.Return(fn(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> Map<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>.Return(fn(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B> Select<T0, T1, T2, T3, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>.Return(fn(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> Select<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>.Return(fn(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>> Select<T0, T1, T2, T3, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, B>.Return(fn(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1)> Combine<T0, T1, T2, T3, S0, S1>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1) => s0.Bind(v0 => s1.Map(v1 => (v0, v1)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2)> Combine<T0, T1, T2, T3, S0, S1, S2>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2) => Combine(s0, s1).Bind(prev => s2.Map(last => (prev.Item1, prev.Item2, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3)> Combine<T0, T1, T2, T3, S0, S1, S2, S3>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3) => Combine(s0, s1, s2).Bind(prev => s3.Map(last => (prev.Item1, prev.Item2, prev.Item3, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4) => Combine(s0, s1, s2, s3).Bind(prev => s4.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5) => Combine(s0, s1, s2, s3, s4).Bind(prev => s5.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5, S6)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5, S6>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S6> s6) => Combine(s0, s1, s2, s3, s4, s5).Bind(prev => s6.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5, S6, S7)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5, S6, S7>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S6> s6, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S7> s7) => Combine(s0, s1, s2, s3, s4, s5, s6).Bind(prev => s7.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5, S6, S7, S8)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5, S6, S7, S8>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S6> s6, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S7> s7, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S8> s8) => Combine(s0, s1, s2, s3, s4, s5, s6, s7).Bind(prev => s8.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S6> s6, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S7> s7, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S8> s8, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S9> s9) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8).Bind(prev => s9.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S6> s6, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S7> s7, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S8> s8, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S9> s9, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S10> s10) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9).Bind(prev => s10.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)> Combine<T0, T1, T2, T3, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S0> s0, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S1> s1, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S2> s2, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S3> s3, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S4> s4, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S5> s5, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S6> s6, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S7> s7, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S8> s8, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S9> s9, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S10> s10, global::FunicularSwitch.Test.MonadA<T0, T1, T2, T3, S11> s11) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10).Bind(prev => s11.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, prev.Item11, last)));
    }
}
