//HintName: FunicularSwitch.Test.MonadABC.g.cs
namespace FunicularSwitch.Test
{
    public readonly partial record struct MonadABC<A>(global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>> M) : global::FunicularSwitch.Transformers.Monad<A>
    {
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static implicit operator MonadABC<A>(global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>> ma) => new(ma);
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static implicit operator global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>(MonadABC<A> ma) => ma.M;
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        global::FunicularSwitch.Transformers.Monad<A_> global::FunicularSwitch.Transformers.Monad<A>.Return<A_>(A_ a) => MonadABC.Return<A_>(a);
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        global::FunicularSwitch.Transformers.Monad<A_> global::FunicularSwitch.Transformers.Monad<A>.Bind<A_>(global::System.Func<A, global::FunicularSwitch.Transformers.Monad<A_>> fn) => this.Bind(a => (MonadABC<A_>)fn(a));
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        A_ global::FunicularSwitch.Transformers.Monad<A>.Cast<A_>() => (A_)(object)M;
    }

    public static partial class MonadABC
    {
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<A> Lift<A>(global::FunicularSwitch.Test.MonadAB<A> ma) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<A>.Return(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> Lift<A>(global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAB<A>> ma) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<A>.Return(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> Lift<A>(global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAB<A>> ma) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<A>.Return(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<A> Return<A>(A a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<A>.Return(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> Return<A>(global::System.Threading.Tasks.Task<A> a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<A>.Return((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> Return<A>(global::System.Threading.Tasks.ValueTask<A> a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<A>.Return((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<B> Bind<A, B>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<B>> Bind<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<B>> Bind<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<B> Bind<A, B>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<B>> Bind<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<B>> Bind<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<B> SelectMany<A, B>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<B>> SelectMany<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<B>> SelectMany<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<B> SelectMany<A, B>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<B>> SelectMany<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<B>> SelectMany<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn) => global::FunicularSwitch.Test.MonadCT.BindT<A, B>((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)((global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<C> SelectMany<A, B, C>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadABC<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadABC<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadABC<B>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadABC<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<C> SelectMany<A, B, C>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadABC<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadABC<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAB<global::FunicularSwitch.Test.MonadC<B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadABC<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<B> Map<A, B>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<B>.Return(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<B>> Map<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<B>.Return(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<B>> Map<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<B>.Return(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<B> Select<A, B>(this global::FunicularSwitch.Test.MonadABC<A> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<B>.Return(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<B>> Select<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<B>.Return(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<B>> Select<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadABC<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadAB.Return(global::FunicularSwitch.Test.MonadC<B>.Return(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1)> Combine<S0, S1>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1) => s0.Bind(v0 => s1.Map(v1 => (v0, v1)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2)> Combine<S0, S1, S2>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2) => Combine(s0, s1).Bind(prev => s2.Map(last => (prev.Item1, prev.Item2, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3)> Combine<S0, S1, S2, S3>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3) => Combine(s0, s1, s2).Bind(prev => s3.Map(last => (prev.Item1, prev.Item2, prev.Item3, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4)> Combine<S0, S1, S2, S3, S4>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4) => Combine(s0, s1, s2, s3).Bind(prev => s4.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5)> Combine<S0, S1, S2, S3, S4, S5>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5) => Combine(s0, s1, s2, s3, s4).Bind(prev => s5.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5, S6)> Combine<S0, S1, S2, S3, S4, S5, S6>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5, global::FunicularSwitch.Test.MonadABC<S6> s6) => Combine(s0, s1, s2, s3, s4, s5).Bind(prev => s6.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5, S6, S7)> Combine<S0, S1, S2, S3, S4, S5, S6, S7>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5, global::FunicularSwitch.Test.MonadABC<S6> s6, global::FunicularSwitch.Test.MonadABC<S7> s7) => Combine(s0, s1, s2, s3, s4, s5, s6).Bind(prev => s7.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5, S6, S7, S8)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5, global::FunicularSwitch.Test.MonadABC<S6> s6, global::FunicularSwitch.Test.MonadABC<S7> s7, global::FunicularSwitch.Test.MonadABC<S8> s8) => Combine(s0, s1, s2, s3, s4, s5, s6, s7).Bind(prev => s8.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5, global::FunicularSwitch.Test.MonadABC<S6> s6, global::FunicularSwitch.Test.MonadABC<S7> s7, global::FunicularSwitch.Test.MonadABC<S8> s8, global::FunicularSwitch.Test.MonadABC<S9> s9) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8).Bind(prev => s9.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5, global::FunicularSwitch.Test.MonadABC<S6> s6, global::FunicularSwitch.Test.MonadABC<S7> s7, global::FunicularSwitch.Test.MonadABC<S8> s8, global::FunicularSwitch.Test.MonadABC<S9> s9, global::FunicularSwitch.Test.MonadABC<S10> s10) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9).Bind(prev => s10.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadABC<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11>(global::FunicularSwitch.Test.MonadABC<S0> s0, global::FunicularSwitch.Test.MonadABC<S1> s1, global::FunicularSwitch.Test.MonadABC<S2> s2, global::FunicularSwitch.Test.MonadABC<S3> s3, global::FunicularSwitch.Test.MonadABC<S4> s4, global::FunicularSwitch.Test.MonadABC<S5> s5, global::FunicularSwitch.Test.MonadABC<S6> s6, global::FunicularSwitch.Test.MonadABC<S7> s7, global::FunicularSwitch.Test.MonadABC<S8> s8, global::FunicularSwitch.Test.MonadABC<S9> s9, global::FunicularSwitch.Test.MonadABC<S10> s10, global::FunicularSwitch.Test.MonadABC<S11> s11) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10).Bind(prev => s11.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, prev.Item11, last)));
    }
}
