//HintName: FunicularSwitch.Test.MonadAB.g.cs
namespace FunicularSwitch.Test
{
    public static partial class MonadAB
    {
        private readonly record struct Impl__FunicularSwitch_Test_MonadA<T0, T1, A>(global::FunicularSwitch.Test.MonadA<T0, T1, A> M) : global::FunicularSwitch.Transformers.Monad<A>
        {
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator Impl__FunicularSwitch_Test_MonadA<T0, T1, A>(global::FunicularSwitch.Test.MonadA<T0, T1, A> ma) => new(ma);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator global::FunicularSwitch.Test.MonadA<T0, T1, A>(Impl__FunicularSwitch_Test_MonadA<T0, T1, A> ma) => ma.M;
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Return<B>(B a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, B>)global::FunicularSwitch.Test.MonadA.Return<T0, T1, B>(a);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Bind<B>(global::System.Func<A, global::FunicularSwitch.Transformers.Monad<B>> fn) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, B>)global::FunicularSwitch.Test.MonadA.Bind(M, a => (global::FunicularSwitch.Test.MonadA<T0, T1, B>)(Impl__FunicularSwitch_Test_MonadA<T0, T1, B>)fn(a));
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public B Cast<B>() => (B)(object)M;
        }

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> Lift<T0, T1, T2, A>(global::FunicularSwitch.Test.MonadA<T0, T1, A> ma) => global::FunicularSwitch.Test.MonadA.Bind(ma, [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>(global::FunicularSwitch.Test.MonadB.Return<T2, A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> Lift<T0, T1, T2, A>(global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>(global::FunicularSwitch.Test.MonadB.Return<T2, A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> Lift<T0, T1, T2, A>(global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>(global::FunicularSwitch.Test.MonadB.Return<T2, A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> Return<T0, T1, T2, A>(A a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>(global::FunicularSwitch.Test.MonadB.Return<T2, A>(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> Return<T0, T1, T2, A>(global::System.Threading.Tasks.Task<A> a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>(global::FunicularSwitch.Test.MonadB.Return<T2, A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> Return<T0, T1, T2, A>(global::System.Threading.Tasks.ValueTask<A> a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>(global::FunicularSwitch.Test.MonadB.Return<T2, A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>> Bind<T0, T1, T2, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T2, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> Bind<T0, T1, T2, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T2, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> Bind<T0, T1, T2, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T2, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>> SelectMany<T0, T1, T2, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T2, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> SelectMany<T0, T1, T2, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T2, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> SelectMany<T0, T1, T2, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T2, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, C>> SelectMany<T0, T1, T2, A, B, C>(this global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, C>>> SelectMany<T0, T1, T2, A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, C>>> SelectMany<T0, T1, T2, A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>> Map<T0, T1, T2, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>(global::FunicularSwitch.Test.MonadB.Return<T2, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> Map<T0, T1, T2, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>(global::FunicularSwitch.Test.MonadB.Return<T2, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> Map<T0, T1, T2, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>(global::FunicularSwitch.Test.MonadB.Return<T2, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>> Select<T0, T1, T2, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>(global::FunicularSwitch.Test.MonadB.Return<T2, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> Select<T0, T1, T2, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>(global::FunicularSwitch.Test.MonadB.Return<T2, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>> Select<T0, T1, T2, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, global::FunicularSwitch.Test.MonadB<T2, B>>(global::FunicularSwitch.Test.MonadB.Return<T2, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1)>> Combine<T0, T1, T2, S0, S1>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1) => global::FunicularSwitch.Test.MonadBT.BindT<T2, S0, (S0, S1)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>>)s0, [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1)>>)(new global::System.Func<S0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1)>>>(v0 => s1.Map<T0, T1, T2, S1, (S0, S1)>(v1 => (v0, v1))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2)>> Combine<T0, T1, T2, S0, S1, S2>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1), (S0, S1, S2)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1)>>)Combine(s0, s1), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2)>>)(new global::System.Func<(S0, S1), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2)>>>(prev => s2.Map<T0, T1, T2, S2, (S0, S1, S2)>(last => (prev.Item1, prev.Item2, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3)>> Combine<T0, T1, T2, S0, S1, S2, S3>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2), (S0, S1, S2, S3)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2)>>)Combine(s0, s1, s2), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3)>>)(new global::System.Func<(S0, S1, S2), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3)>>>(prev => s3.Map<T0, T1, T2, S3, (S0, S1, S2, S3)>(last => (prev.Item1, prev.Item2, prev.Item3, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3), (S0, S1, S2, S3, S4)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3)>>)Combine(s0, s1, s2, s3), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4)>>)(new global::System.Func<(S0, S1, S2, S3), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4)>>>(prev => s4.Map<T0, T1, T2, S4, (S0, S1, S2, S3, S4)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4), (S0, S1, S2, S3, S4, S5)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4)>>)Combine(s0, s1, s2, s3, s4), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5)>>)(new global::System.Func<(S0, S1, S2, S3, S4), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5)>>>(prev => s5.Map<T0, T1, T2, S5, (S0, S1, S2, S3, S4, S5)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5, S6>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S6>> s6) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4, S5), (S0, S1, S2, S3, S4, S5, S6)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5)>>)Combine(s0, s1, s2, s3, s4, s5), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6)>>>(prev => s6.Map<T0, T1, T2, S6, (S0, S1, S2, S3, S4, S5, S6)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5, S6, S7>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S6>> s6, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S7>> s7) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4, S5, S6), (S0, S1, S2, S3, S4, S5, S6, S7)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6)>>)Combine(s0, s1, s2, s3, s4, s5, s6), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7)>>>(prev => s7.Map<T0, T1, T2, S7, (S0, S1, S2, S3, S4, S5, S6, S7)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5, S6, S7, S8>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S6>> s6, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S7>> s7, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S8>> s8) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4, S5, S6, S7), (S0, S1, S2, S3, S4, S5, S6, S7, S8)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>>>(prev => s8.Map<T0, T1, T2, S8, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S6>> s6, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S7>> s7, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S8>> s8, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S9>> s9) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8), (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7, S8), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>>(prev => s9.Map<T0, T1, T2, S9, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S6>> s6, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S7>> s7, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S8>> s8, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S9>> s9, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S10>> s10) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9), (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>>(prev => s10.Map<T0, T1, T2, S10, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>> Combine<T0, T1, T2, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11>(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S0>> s0, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S1>> s1, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S2>> s2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S3>> s3, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S4>> s4, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S5>> s5, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S6>> s6, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S7>> s7, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S8>> s8, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S9>> s9, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S10>> s10, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, S11>> s11) => global::FunicularSwitch.Test.MonadBT.BindT<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10), (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>((Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>)(global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10), global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>>>(prev => s11.Map<T0, T1, T2, S11, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, prev.Item11, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>> Flatten<T0, T1, T2, A>(this global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>>> ma) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => a);

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> Flatten<T0, T1, T2, A>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>>>> ma) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => a);

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>> Flatten<T0, T1, T2, A>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, global::FunicularSwitch.Test.MonadA<T0, T1, global::FunicularSwitch.Test.MonadB<T2, A>>>>> ma) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => a);
    }
}
