//HintName: FunicularSwitch.Test.MonadAB.g.cs
namespace FunicularSwitch.Test
{
    public static partial class MonadAB
    {
        private readonly record struct Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, A>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, A> M) : global::FunicularSwitch.Transformers.Monad<A>
        {
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, A>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, A> ma) => new(ma);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator global::FunicularSwitch.Test.MonadA<T0, T1, T2, A>(Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, A> ma) => ma.M;
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Return<B>(B a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, B>)global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, B>(a);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Bind<B>(global::System.Func<A, global::FunicularSwitch.Transformers.Monad<B>> fn) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, B>)global::FunicularSwitch.Test.MonadA.Bind(M, a => (global::FunicularSwitch.Test.MonadA<T0, T1, T2, B>)(Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, B>)fn(a));
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public B Cast<B>() => (B)(object)M;
        }

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> Lift<T0, T1, T2, T3, T4, T5, A>(global::FunicularSwitch.Test.MonadA<T0, T1, T2, A> ma) => global::FunicularSwitch.Test.MonadA.Bind(ma, [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> Lift<T0, T1, T2, T3, T4, T5, A>(global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> Lift<T0, T1, T2, T3, T4, T5, A>(global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> Return<T0, T1, T2, T3, T4, T5, A>(A a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, A>(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> Return<T0, T1, T2, T3, T4, T5, A>(global::System.Threading.Tasks.Task<A> a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> Return<T0, T1, T2, T3, T4, T5, A>(global::System.Threading.Tasks.ValueTask<A> a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>> Bind<T0, T1, T2, T3, T4, T5, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T3, T4, T5, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> Bind<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T3, T4, T5, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> Bind<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T3, T4, T5, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>> SelectMany<T0, T1, T2, T3, T4, T5, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T3, T4, T5, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> SelectMany<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T3, T4, T5, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> SelectMany<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<T3, T4, T5, A, B>((Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, C>> SelectMany<T0, T1, T2, T3, T4, T5, A, B, C>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, C>>> SelectMany<T0, T1, T2, T3, T4, T5, A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, C>>> SelectMany<T0, T1, T2, T3, T4, T5, A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>> Map<T0, T1, T2, T3, T4, T5, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> Map<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> Map<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>> Select<T0, T1, T2, T3, T4, T5, A, B>(this global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> Select<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>> Select<T0, T1, T2, T3, T4, T5, A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<T0, T1, T2, global::FunicularSwitch.Test.MonadB<T3, T4, T5, B>>(global::FunicularSwitch.Test.MonadB.Return<T3, T4, T5, B>(fn(a))));
    }
}
