//HintName: FunicularSwitch.Test.MonadAB.g.cs
namespace FunicularSwitch.Test
{
    public static partial class MonadAB
    {
        private readonly record struct Impl__FunicularSwitch_Test_MonadA<A>(global::FunicularSwitch.Test.MonadA<A> M) : global::FunicularSwitch.Transformers.Monad<A>
        {
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator Impl__FunicularSwitch_Test_MonadA<A>(global::FunicularSwitch.Test.MonadA<A> ma) => new(ma);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator global::FunicularSwitch.Test.MonadA<A>(Impl__FunicularSwitch_Test_MonadA<A> ma) => ma.M;
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Return<B>(B a) => (Impl__FunicularSwitch_Test_MonadA<B>)global::FunicularSwitch.Test.MonadA.Return<B>(a);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Bind<B>(global::System.Func<A, global::FunicularSwitch.Transformers.Monad<B>> fn) => (Impl__FunicularSwitch_Test_MonadA<B>)global::FunicularSwitch.Test.MonadA.Bind(M, a => (global::FunicularSwitch.Test.MonadA<B>)(Impl__FunicularSwitch_Test_MonadA<B>)fn(a));
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public B Cast<B>() => (B)(object)M;
        }

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> Lift<A>(global::FunicularSwitch.Test.MonadA<A> ma) => global::FunicularSwitch.Test.MonadA.Bind(ma, [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> Lift<A>(global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> Lift<A>(global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> Return<A>(A a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> Return<A>(global::System.Threading.Tasks.Task<A> a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> Return<A>(global::System.Threading.Tasks.ValueTask<A> a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>> Bind<A, B>(this global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> Bind<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> Bind<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>> SelectMany<A, B>(this global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> SelectMany<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> SelectMany<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<C>> SelectMany<A, B, C>(this global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<C>>> SelectMany<A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<C>>> SelectMany<A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>> Map<A, B>(this global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> Map<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> Map<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>> Select<A, B>(this global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> Select<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> Select<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1)>> Combine<S0, S1>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1) => s0.Bind(v0 => s1.Map(v1 => (v0, v1)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2)>> Combine<S0, S1, S2>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2) => Combine(s0, s1).Bind(prev => s2.Map(last => (prev.Item1, prev.Item2, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3)>> Combine<S0, S1, S2, S3>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3) => Combine(s0, s1, s2).Bind(prev => s3.Map(last => (prev.Item1, prev.Item2, prev.Item3, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4)>> Combine<S0, S1, S2, S3, S4>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4) => Combine(s0, s1, s2, s3).Bind(prev => s4.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5)>> Combine<S0, S1, S2, S3, S4, S5>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5) => Combine(s0, s1, s2, s3, s4).Bind(prev => s5.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6)>> Combine<S0, S1, S2, S3, S4, S5, S6>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S6>> s6) => Combine(s0, s1, s2, s3, s4, s5).Bind(prev => s6.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7)>> Combine<S0, S1, S2, S3, S4, S5, S6, S7>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S6>> s6, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S7>> s7) => Combine(s0, s1, s2, s3, s4, s5, s6).Bind(prev => s7.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)>> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S6>> s6, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S7>> s7, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S8>> s8) => Combine(s0, s1, s2, s3, s4, s5, s6, s7).Bind(prev => s8.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S6>> s6, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S7>> s7, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S8>> s8, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S9>> s9) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8).Bind(prev => s9.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S6>> s6, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S7>> s7, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S8>> s8, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S9>> s9, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S10>> s10) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9).Bind(prev => s10.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, last)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>> s0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S1>> s1, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S2>> s2, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S3>> s3, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S4>> s4, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S5>> s5, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S6>> s6, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S7>> s7, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S8>> s8, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S9>> s9, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S10>> s10, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S11>> s11) => Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10).Bind(prev => s11.Map(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, prev.Item11, last)));
    }
}
