//HintName: FunicularSwitch.Test.MonadAMonadB.g.cs
namespace FunicularSwitch.Test
{
    public partial record struct MonadAMonadB<A>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> M) : global::FunicularSwitch.Transformers.Monad<A>
    {
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static implicit operator MonadAMonadB<A>(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>> ma) => new(ma);
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static implicit operator global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>(MonadAMonadB<A> ma) => ma.M;
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        global::FunicularSwitch.Transformers.Monad<A_> global::FunicularSwitch.Transformers.Monad<A>.Return<A_>(A_ a) => MonadAMonadB.Return<A_>(a);
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        global::FunicularSwitch.Transformers.Monad<A_> global::FunicularSwitch.Transformers.Monad<A>.Bind<A_>(global::System.Func<A, global::FunicularSwitch.Transformers.Monad<A_>> fn) => this.Bind(a => (MonadAMonadB<A_>)fn(a));
        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        A_ global::FunicularSwitch.Transformers.Monad<A>.Cast<A_>() => (A_)(object)M;
    }

    public static partial class MonadAMonadB
    {
        private readonly record struct Impl__FunicularSwitch_Test_MonadA<A>(global::FunicularSwitch.Test.MonadA<A> M) : global::FunicularSwitch.Transformers.Monad<A>
        {
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator Impl__FunicularSwitch_Test_MonadA<A>(global::FunicularSwitch.Test.MonadA<A> ma) => new(ma);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public static implicit operator global::FunicularSwitch.Test.MonadA<A>(Impl__FunicularSwitch_Test_MonadA<A> ma) => ma.M;
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Return<B>(B a) => (Impl__FunicularSwitch_Test_MonadA<B>)global::FunicularSwitch.Test.MonadA.Return<B>(a);
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public global::FunicularSwitch.Transformers.Monad<B> Bind<B>(global::System.Func<A, global::FunicularSwitch.Transformers.Monad<B>> fn) => (Impl__FunicularSwitch_Test_MonadA<B>)global::FunicularSwitch.Test.MonadA.Bind(M, a => (global::FunicularSwitch.Test.MonadA<B>)(Impl__FunicularSwitch_Test_MonadA<B>)fn(a));
            [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
            public B Cast<B>() => (B)(object)M;
        }

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<A> Lift<A>(global::FunicularSwitch.Test.MonadA<A> ma) => global::FunicularSwitch.Test.MonadA.Bind(ma, [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> Lift<A>(global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadA<A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> Lift<A>(global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadA<A>> ma) => global::FunicularSwitch.Test.MonadA.Bind((await ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<A> Return<A>(A a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>(a));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> Return<A>(global::System.Threading.Tasks.Task<A> a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> Return<A>(global::System.Threading.Tasks.ValueTask<A> a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<A>>(global::FunicularSwitch.Test.MonadB.Return<A>((await a)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<B> Bind<A, B>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<B>> Bind<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<B>> Bind<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<B> Bind<A, B>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<B>> Bind<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<B>> Bind<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<B> SelectMany<A, B>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<B>> SelectMany<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<B>> SelectMany<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<B> SelectMany<A, B>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)ma), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<B>> SelectMany<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<B>> SelectMany<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn) => global::FunicularSwitch.Test.MonadBT.BindT<A, B>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<A>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)((global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<A>>)(await ma)), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<B>>)(new global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => fn(a)).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<C> SelectMany<A, B, C>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadAMonadB<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadAMonadB<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadAMonadB<B>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadAMonadB<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<C> SelectMany<A, B, C>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn, global::System.Func<A, B, C> selector) => ma.SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadAMonadB<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadAMonadB<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<C>> SelectMany<A, B, C>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<B>>> fn, global::System.Func<A, B, C> selector) => (await ma).SelectMany([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => ((global::FunicularSwitch.Test.MonadAMonadB<B>)fn(a)).Map([global::System.Diagnostics.DebuggerStepThroughAttribute](b) => selector(a, b)));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<B> Map<A, B>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<B>> Map<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<B>> Map<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<B> Select<A, B>(this global::FunicularSwitch.Test.MonadAMonadB<A> ma, global::System.Func<A, B> fn) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<B>> Select<A, B>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<B>> Select<A, B>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> ma, global::System.Func<A, B> fn) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => global::FunicularSwitch.Test.MonadA.Return<global::FunicularSwitch.Test.MonadB<B>>(global::FunicularSwitch.Test.MonadB.Return<B>(fn(a))));

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1)> Combine<S0, S1>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1) => global::FunicularSwitch.Test.MonadBT.BindT<S0, (S0, S1)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<S0>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<S0>>)s0, [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1)>>)(new global::System.Func<S0, global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1)>>>(v0 => s1.Map<S1, (S0, S1)>(v1 => (v0, v1))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2)> Combine<S0, S1, S2>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1), (S0, S1, S2)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1)>>)Combine(s0, s1), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2)>>)(new global::System.Func<(S0, S1), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2)>>>(prev => s2.Map<S2, (S0, S1, S2)>(last => (prev.Item1, prev.Item2, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3)> Combine<S0, S1, S2, S3>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2), (S0, S1, S2, S3)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2)>>)Combine(s0, s1, s2), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3)>>)(new global::System.Func<(S0, S1, S2), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3)>>>(prev => s3.Map<S3, (S0, S1, S2, S3)>(last => (prev.Item1, prev.Item2, prev.Item3, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4)> Combine<S0, S1, S2, S3, S4>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3), (S0, S1, S2, S3, S4)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3)>>)Combine(s0, s1, s2, s3), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4)>>)(new global::System.Func<(S0, S1, S2, S3), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4)>>>(prev => s4.Map<S4, (S0, S1, S2, S3, S4)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5)> Combine<S0, S1, S2, S3, S4, S5>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4), (S0, S1, S2, S3, S4, S5)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4)>>)Combine(s0, s1, s2, s3, s4), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5)>>)(new global::System.Func<(S0, S1, S2, S3, S4), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5)>>>(prev => s5.Map<S5, (S0, S1, S2, S3, S4, S5)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5, S6)> Combine<S0, S1, S2, S3, S4, S5, S6>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5, global::FunicularSwitch.Test.MonadAMonadB<S6> s6) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4, S5), (S0, S1, S2, S3, S4, S5, S6)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5)>>)Combine(s0, s1, s2, s3, s4, s5), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6)>>>(prev => s6.Map<S6, (S0, S1, S2, S3, S4, S5, S6)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5, S6, S7)> Combine<S0, S1, S2, S3, S4, S5, S6, S7>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5, global::FunicularSwitch.Test.MonadAMonadB<S6> s6, global::FunicularSwitch.Test.MonadAMonadB<S7> s7) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4, S5, S6), (S0, S1, S2, S3, S4, S5, S6, S7)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6)>>)Combine(s0, s1, s2, s3, s4, s5, s6), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7)>>>(prev => s7.Map<S7, (S0, S1, S2, S3, S4, S5, S6, S7)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5, global::FunicularSwitch.Test.MonadAMonadB<S6> s6, global::FunicularSwitch.Test.MonadAMonadB<S7> s7, global::FunicularSwitch.Test.MonadAMonadB<S8> s8) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4, S5, S6, S7), (S0, S1, S2, S3, S4, S5, S6, S7, S8)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)>>>(prev => s8.Map<S8, (S0, S1, S2, S3, S4, S5, S6, S7, S8)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5, global::FunicularSwitch.Test.MonadAMonadB<S6> s6, global::FunicularSwitch.Test.MonadAMonadB<S7> s7, global::FunicularSwitch.Test.MonadAMonadB<S8> s8, global::FunicularSwitch.Test.MonadAMonadB<S9> s9) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4, S5, S6, S7, S8), (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7, S8), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>>(prev => s9.Map<S9, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5, global::FunicularSwitch.Test.MonadAMonadB<S6> s6, global::FunicularSwitch.Test.MonadAMonadB<S7> s7, global::FunicularSwitch.Test.MonadAMonadB<S8> s8, global::FunicularSwitch.Test.MonadAMonadB<S9> s9, global::FunicularSwitch.Test.MonadAMonadB<S10> s10) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9), (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>>(prev => s10.Map<S10, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)> Combine<S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11>(global::FunicularSwitch.Test.MonadAMonadB<S0> s0, global::FunicularSwitch.Test.MonadAMonadB<S1> s1, global::FunicularSwitch.Test.MonadAMonadB<S2> s2, global::FunicularSwitch.Test.MonadAMonadB<S3> s3, global::FunicularSwitch.Test.MonadAMonadB<S4> s4, global::FunicularSwitch.Test.MonadAMonadB<S5> s5, global::FunicularSwitch.Test.MonadAMonadB<S6> s6, global::FunicularSwitch.Test.MonadAMonadB<S7> s7, global::FunicularSwitch.Test.MonadAMonadB<S8> s8, global::FunicularSwitch.Test.MonadAMonadB<S9> s9, global::FunicularSwitch.Test.MonadAMonadB<S10> s10, global::FunicularSwitch.Test.MonadAMonadB<S11> s11) => global::FunicularSwitch.Test.MonadBT.BindT<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10), (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>((Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>)(global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10)>>)Combine(s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10), [global::System.Diagnostics.DebuggerStepThroughAttribute](a) => (Impl__FunicularSwitch_Test_MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>>)(new global::System.Func<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10), global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>>>(prev => s11.Map<S11, (S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>(last => (prev.Item1, prev.Item2, prev.Item3, prev.Item4, prev.Item5, prev.Item6, prev.Item7, prev.Item8, prev.Item9, prev.Item10, prev.Item11, last))).Invoke(a))).Cast<global::FunicularSwitch.Test.MonadA<global::FunicularSwitch.Test.MonadB<(S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11)>>>();

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static global::FunicularSwitch.Test.MonadAMonadB<A> Flatten<A>(this global::FunicularSwitch.Test.MonadAMonadB<global::FunicularSwitch.Test.MonadAMonadB<A>> ma) => ma.Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => a);

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<A>> Flatten<A>(this global::System.Threading.Tasks.Task<global::FunicularSwitch.Test.MonadAMonadB<global::FunicularSwitch.Test.MonadAMonadB<A>>> ma) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => a);

        [global::System.Diagnostics.Contracts.PureAttribute, global::System.Diagnostics.DebuggerStepThroughAttribute]
        public static async global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<A>> Flatten<A>(this global::System.Threading.Tasks.ValueTask<global::FunicularSwitch.Test.MonadAMonadB<global::FunicularSwitch.Test.MonadAMonadB<A>>> ma) => (await ma).Bind([global::System.Diagnostics.DebuggerStepThroughAttribute](a) => a);
    }
}
